apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: coolstore-prod
  finalizers:
    # The default behaviour is foreground cascading deletion
    - resources-finalizer.argocd.argoproj.io  
spec:
  destination:
    namespace: coolstore-prod
    name: in-cluster
  project: default
  source:
    path: examples/coolstore/overlays/prod
    repoURL: https://github.com/cainza/openshift-gitops-demo.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true      